# Site settings
author: AJ
title: Flatiron School -Learn Co Blog 
header-img: img/home-bg.png
email: ashiguiles@gmail.com
copyright_name: AJ
description: > # this means to ignore newlines until "baseurl:"
  Learning With Flatiron School 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AG2791

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
